import { defineConfig, loadEnv } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import tsConfigPaths from "vite-tsconfig-paths";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import { readFileSync, writeFileSync } from "node:fs";

// ---------------------------------------------------------------------------
// Strip TypeScript type-only footer that TanStack Router appends to the
// auto-generated routeTree.gen.js — not needed in a plain JS project.
// ---------------------------------------------------------------------------
const ROUTE_TREE_FILE = "src/routeTree.gen.js";

function stripTanStackTypeFooter(code) {
  return code.replace(
    /\nimport type \{ getRouter \}[\s\S]*?declare module '@tanstack\/react-start' \{[\s\S]*?\n\}\n?/m,
    "\n",
  );
}

function stripTanStackTypeFooterPlugin() {
  return {
    name: "strip-tanstack-type-footer",
    enforce: "pre",
    buildStart() {
      try {
        const code = readFileSync(ROUTE_TREE_FILE, "utf8");
        const stripped = stripTanStackTypeFooter(code);
        if (stripped !== code) writeFileSync(ROUTE_TREE_FILE, stripped);
      } catch {
        // TanStack may create the file after this hook on a fresh checkout.
      }
    },
    transform(code, id) {
      if (!id.replaceAll("\\", "/").endsWith(ROUTE_TREE_FILE)) return null;
      const stripped = stripTanStackTypeFooter(code);
      if (stripped !== code) {
        writeFileSync(ROUTE_TREE_FILE, stripped);
        return { code: stripped, map: null };
      }
      return null;
    },
  };
}

// ---------------------------------------------------------------------------
// Main config
// ---------------------------------------------------------------------------
export default defineConfig(({ command, mode }) => {
  // Inject VITE_* env vars as static replacements (mirrors Lovable wrapper behaviour)
  const loadedEnv = loadEnv(mode, process.cwd(), "VITE_");
  const envDefine = {};
  for (const [key, value] of Object.entries(loadedEnv)) {
    envDefine[`import.meta.env.${key}`] = JSON.stringify(value);
  }

  return {
    define: envDefine,

    plugins: [
      // Path alias resolution (@/* → src/*)
      tsConfigPaths({ projects: ["./tsconfig.json"] }),

      // TanStack Start (SSR + server functions + file-based routing)
      tanstackStart({
        importProtection: {
          behavior: "error",
          client: { files: ["**/server/**"], specifiers: ["server-only"] },
        },
        router: {
          disableTypes: true,
          generatedRouteTree: "routeTree.gen.js",
          routeTreeFileHeader: [
            "// This file was automatically generated by TanStack Router.",
            "// Do not edit this file directly.",
          ],
        },
        server: { entry: "server" },
      }),

      // Tailwind CSS v4
      tailwindcss(),

      // React fast-refresh + JSX transform
      react(),

      // Strip TS type footer from auto-generated route tree
      stripTanStackTypeFooterPlugin(),
    ],

    resolve: {
      alias: { "@": `${process.cwd()}/src` },
      dedupe: [
        "react",
        "react-dom",
        "react/jsx-runtime",
        "react/jsx-dev-runtime",
        "@tanstack/react-query",
        "@tanstack/query-core",
      ],
    },

    css: { transformer: "lightningcss" },

    optimizeDeps: {
      include: [
        "react",
        "react-dom",
        "react-dom/client",
        "react/jsx-runtime",
        "react/jsx-dev-runtime",
      ],
      ignoreOutdatedRequests: true,
    },

    server: {
      host: "::",
      port: 8080,
    },
  };
});
