// @lovable.dev/vite-tanstack-config already includes the following - do NOT add them manually
// or the app will break with duplicate plugins:
//   - tanstackStart, viteReact, tailwindcss, tsConfigPaths, nitro (build-only using cloudflare as a default target),
//     componentTagger (dev-only), VITE_* env injection, @ path alias, React/TanStack dedupe,
//     error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... }, etc... }) if needed.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";
import { readFileSync, writeFileSync } from "node:fs";

const ROUTE_TREE_FILE = "src/routeTree.gen.js";

function stripTanStackTypeFooter(code) {
  return code.replace(
    /\nimport type \{ getRouter \}[\s\S]*?declare module '@tanstack\/react-start' \{[\s\S]*?\n\}\n?/m,
    "\n",
  );
}

function stripTanStackTypeFooterPlugin() {
  return {
    name: "strip-tanstack-type-footer",
    enforce: "pre",
    buildStart() {
      try {
        const code = readFileSync(ROUTE_TREE_FILE, "utf8");
        const stripped = stripTanStackTypeFooter(code);
        if (stripped !== code) {
          writeFileSync(ROUTE_TREE_FILE, stripped);
        }
      } catch {
        // TanStack may create the file after this hook on a fresh checkout.
      }
    },
    transform(code, id) {
      if (!id.replaceAll("\\", "/").endsWith(ROUTE_TREE_FILE)) return null;

      const stripped = stripTanStackTypeFooter(code);
      if (stripped !== code) {
        writeFileSync(ROUTE_TREE_FILE, stripped);
        return { code: stripped, map: null };
      }

      return null;
    },
  };
}

export default defineConfig({
  plugins: [stripTanStackTypeFooterPlugin()],
  tanstackStart: {
    router: {
      disableTypes: true,
      generatedRouteTree: "routeTree.gen.js",
      routeTreeFileHeader: [
        "// This file was automatically generated by TanStack Router.",
        "// Do not edit this file directly.",
      ],
    },
    // Redirect TanStack Start's bundled server entry to src/server.js (our SSR error wrapper).
    // nitro/vite builds from this
    server: { entry: "server" },
  },
});
