version = 0.1

[default.deploy.parameters]
stack_name = "dawaa-backend-dev"
resolve_s3 = true
s3_prefix = "dawaa-backend-dev"
profile = "dawaa-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GoogleMapsApiKey=\"\" UsersTableName=\"DawaaUsers\" InventoryTableName=\"DawaaInventory\" PharmaciesTableName=\"DawaaPharmacies\" MedicinesTableName=\"DawaaMedicines\""
image_repositories = []

[default.global.parameters]
region = "eu-north-1"
